### ISSUE TITLE
Can you tweak your Author info?

### ISSUE THREAD

**Issue by pbrisbin** [pSub/yesod-rst#1]
This is very random and unimportant, but I've been using [packadeps](https://packdeps.haskellers.com/) to keep an eye on overly-restrictive upper bounds on my packages. Since you have "based on code from Patrick Brisbin" in your Author field, your package keeps popping up in my notifications.

Would you mind removing that, maybe mentioning me in README instead?

I know it's silly, but I thought I'd ask.

**Comment by pSub** [comment]
I've tweaked author info in the cabal file. I guess I need to upload a new version as well to fix your problem right? I'll try to do so, but I haven't done this in years. I need to figure out how this used to work. ;)

**Comment by pbrisbin** [comment]
Thanks for taking a look! No worries either way.
